app:
  services:
    orders: https://tap-otel-orders.dev-ns.tap.jkcloudmesh.com
    items: https://tap-otel-items.dev-ns.tap.jkcloudmesh.com

server:
  port: ${PORT:8080}

management:
  metrics:
    export:
      wavefront:
        uri: proxy://wavefront-proxy.wavefront.svc.cluster.local:2878
