app:
  services:
    orders: https://tap-otel-orders.dev-ns.tap.jkcloudmesh.com
    items: https://tap-otel-items.dev-ns.tap.jkcloudmesh.com

server:
  port: ${PORT:8080}

management:
  tracing:
    enabled: true
  otlp:
    metrics:
      export:
        enabled: true
